/** Seeded Opera House memories — from Google Sheet Memories Database (Opera House only). */

export const RELATIONSHIP_LABELS = {
  firstTime: "First time",
  often: "I come here often",
  usedTo: "I used to come here",
  passingThrough: "I was passing through",
};

export const REGION_LABELS = {
  steps: "The steps",
  sails: "The sails",
  harbour: "The harbour",
  forecourt: "The forecourt",
};

export const MAX_BODY_CHARS = 280;

export const LEAVE_PROMPT =
  "What happened here that you might still remember later?";

/** Short unpolished title from body text. */
export function autoTitleFromBody(body = "") {
  const cleaned = String(body).trim().replace(/\s+/g, " ");
  if (!cleaned) return "A memory";
  const first = cleaned.split(/[.!?]/)[0]?.trim() || cleaned;
  const words = first.split(" ").slice(0, 4).join(" ");
  const title = words.length > 28 ? `${words.slice(0, 26).trim()}…` : words;
  return title || "A memory";
}

/**
 * Opera House seed from sheet. Bodies unchanged.
 * title = short in-scene label; region for pin placement.
 */
export const memories = [
  {
    id: "m01",
    title: "I wandered without checking",
    body: "I wandered without checking the time. A person beside me lowered their camera and simply looked, which gave me permission to do the same. The stone forecourt changed as the light moved across the scene. The harbour is part of everyday life here, so I liked seeing it outside the usual rush. The longer I remained there, the less important my original reason for visiting seemed. The memory reminds me that delight can hide inside very ordinary plans. I still associate that feeling with Opera House in 2021. I did not expect to leave carrying a bright rush of joy. A family debated where to stand for a photo, and I quietly smiled because we had done the same thing earlier. I nearly skipped this stop because I was tired, but curiosity won the argument.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Joy",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m02",
    title: "That was the point",
    body: "That was the point when I stopped treating the visit as something I had to complete. I did not expect the day to become memorable, which is probably why it did. I still associate that feeling with Opera House in 2022. The steps facing the harbour changed as the light moved across the scene. The plan was simple: meet someone, look around, and keep moving. We did none of that in a hurry. An unexpected joke from someone nearby broke the seriousness of my thoughts. I called a friend before I had even left. I did not expect to leave carrying a burst of uncomplicated happiness. Sydney is full of views that locals can accidentally become blind to, and that afternoon corrected me. I remember the sound of water moving against the quay almost as clearly as the view itself.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Joy",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m03",
    title: "The strongest part of",
    body: "The strongest part of the afternoon was a warm sense of celebration. I did not need another activity to justify being there. I had expected the famous view, but the everyday movement around it was what made the visit feel real. That simple afternoon still makes me smile when I think about it. The detail that survives most clearly is the smell of rain on stone. I wandered without checking the time. The broad harbour steps changed as the light moved across the scene. An unexpected joke from someone nearby broke the seriousness of my thoughts. Someone held a coffee in both hands against the wind, and that tiny gesture made the weather suddenly noticeable. I went there expecting a familiar Sydney view and somehow ended up seeing it with fresh eyes.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Joy",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m04",
    title: "The broad harbour steps",
    body: "The broad harbour steps changed as the light moved across the scene. I did not need another activity to justify being there. The first thing I noticed was not the landmark itself but the people moving around it. A person beside me lowered their camera and simply looked, which gave me permission to do the same. For a moment, everyone seemed to pause at once before the crowd started moving again. I kept comparing what I had imagined from photographs with what was actually in front of me. The strongest part of the afternoon was a warm sense of celebration. I remember how easy it felt to enjoy the city without needing a reason. I still associate that feeling with Opera House in 2024. I bought myself a small treat nearby.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Joy",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m05",
    title: "A changing light on",
    body: "A changing light on the sails became the detail I kept noticing whenever I looked away and then back again. The strongest part of the afternoon was a bright rush of joy. As a first visit, the place felt less like a postcard and more like a living part of the city. That was the point when I stopped treating the visit as something I had to complete. The white sails changed as the light moved across the scene. I nearly skipped this stop because I was tired, but curiosity won the argument. I took far too many photos. The memory reminds me that delight can hide inside very ordinary plans. I think that is why the visit stayed with me long after I had left Opera House. An unexpected joke from someone nearby broke the seriousness of my thoughts.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Joy",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m06",
    title: "Someone held a coffee",
    body: "Someone held a coffee in both hands against the wind, and that tiny gesture made the weather suddenly noticeable. The familiarity was comforting because this was a place I could reach without turning the day into an event. I took far too many photos. The broad harbour steps changed as the light moved across the scene. What began as a quick stop gradually became a moment I wanted to remember accurately. The open space beside the sails changed as the light moved across the scene. The visit began between errands, which made the calm that followed feel even more unexpected. The happiness came from being present enough to notice everything. I still associate that feeling with Opera House in 2026. I did not expect to leave carrying a warm sense of celebration.",
    relationship: "passingThrough",
    region: "sails",
    emotion: "Joy",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m07",
    title: "The broad harbour steps",
    body: "The broad harbour steps changed as the light moved across the scene. Sydney is full of views that locals can accidentally become blind to, and that afternoon corrected me. A stranger laughed as they hurried past, and the tiny interruption somehow made the scene feel more human. I remember less about the itinerary than I remember feeling close. I still associate that feeling with Opera House in 2021. I did not need another activity to justify being there. I was surprised by how strongly I felt a quiet feeling of being close to someone. I remember the sound of small bursts of laughter almost as clearly as the view itself. An unexpected joke from someone nearby broke the seriousness of my thoughts. I noticed how naturally our conversation slowed down.",
    relationship: "passingThrough",
    region: "steps",
    emotion: "Love",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m08",
    title: "A ferry moved through",
    body: "A ferry moved through the distance while people around me carried on with conversations that had nothing to do with the view. I had the strange feeling of being both a resident and an observer for a few minutes. The steps facing the harbour stayed in view while the crowd, weather and sounds kept rearranging the moment. I did not need another activity to justify being there. Underneath everything else, there was a deep sense of affection. We sat together and watched the light change. A person beside me lowered their camera and simply looked, which gave me permission to do the same. The open space beside the sails changed as the light moved across the scene. It was a small moment, but it made the city feel unusually personal. I still associate that feeling with Opera House in 2022.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Love",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m09",
    title: "There was a brief",
    body: "There was a brief pause in the day when everyone around me seemed to be doing exactly what they wanted. Years later, the strongest part of the memory is still the sense of togetherness. The detail that survives most clearly is the smell of rain on stone. Coming from overseas, I had seen the landmark online, but the real scale was completely different. I did not need another activity to justify being there. Someone nearby was taking photos, but I found myself watching the broad harbour steps instead. For a moment, everyone seemed to pause at once before the crowd started moving again. An unexpected joke from someone nearby broke the seriousness of my thoughts. I was surprised by how strongly I felt a deep sense of affection. We took turns choosing what to photograph.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Love",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m10",
    title: "The white sails changed",
    body: "The white sails changed as the light moved across the scene. Somewhere between the noise and the pauses, I noticed a tenderness I did not want to rush. I could feel sun-warmed paving, and that small physical detail made the memory unusually concrete. We sat together and watched the light change. I remember arriving with my head full of other things and leaving with room for something else. The place became meaningful because of the person beside me. Even now, I can picture the stone forecourt and remember exactly how the air felt. The harbour is part of everyday life here, so I liked seeing it outside the usual rush. I did not need another activity to justify being there. For a moment, everyone seemed to pause at once before the crowd started moving again.",
    relationship: "firstTime",
    region: "forecourt",
    emotion: "Love",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m11",
    title: "Somewhere between the noise",
    body: "Somewhere between the noise and the pauses, I noticed a deep sense of affection. For a moment, everyone seemed to pause at once before the crowd started moving again. There was a brief pause in the day when everyone around me seemed to be doing exactly what they wanted. I did not need another activity to justify being there. The steps facing the harbour changed as the light moved across the scene. I was still learning the city's rhythm, so even ordinary details felt surprisingly vivid. I remember less about the itinerary than I remember feeling close. I still associate that feeling with Opera House in 2025. A family debated where to stand for a photo, and I quietly smiled because we had done the same thing earlier. We shared food and watched the harbour together.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Love",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m12",
    title: "An unexpected joke from",
    body: "An unexpected joke from someone nearby broke the seriousness of my thoughts. I remember less about the itinerary than I remember feeling close. The detail that survives most clearly is the smell of rain on stone. I remember checking the time before I arrived and forgetting to check it again afterward. I did not expect to leave carrying a strong sense of connection. I had the strange feeling of being both a resident and an observer for a few minutes. We sat together and watched the light change. The stone forecourt changed as the light moved across the scene. Every few minutes, a different sound — especially small bursts of laughter — changed the atmosphere slightly. What began as a quick stop gradually became a moment I wanted to remember accurately.",
    relationship: "passingThrough",
    region: "forecourt",
    emotion: "Love",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m13",
    title: "I compared the view",
    body: "I compared the view with an old photo in my phone. I realised I was no longer looking for the 'best' angle; I was simply paying attention. The place felt new and familiar at the same time. I still associate that feeling with Opera House in 2021. The plan was simple: meet someone, look around, and keep moving. We did none of that in a hurry. An unexpected joke from someone nearby broke the seriousness of my thoughts. I had the strange feeling of being both a resident and an observer for a few minutes. I remember the sound of distant traffic almost as clearly as the view itself. For a moment, everyone seemed to pause at once before the crowd started moving again. I did not expect to leave carrying a gentle pull toward the past.",
    relationship: "usedTo",
    region: "forecourt",
    emotion: "Nostalgia",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m14",
    title: "The city seemed to",
    body: "The city seemed to hold several versions of my life at once. I still associate that feeling with Opera House in 2022. I was surprised by how strongly I felt a familiar ache of remembrance. The air carried the soft spray from the water, while the broad harbour steps held most of my attention. The edge of Circular Quay changed as the light moved across the scene. I compared the view with an old photo in my phone. I had no special occasion to celebrate that day, only a little spare time and the urge to use it well. I did not need another activity to justify being there. I had the strange feeling of being both a resident and an observer for a few minutes. For a moment, everyone seemed to pause at once before the crowd started moving again.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Nostalgia",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m15",
    title: "An unexpected joke from",
    body: "An unexpected joke from someone nearby broke the seriousness of my thoughts. I was travelling without a strict schedule, which gave me permission to stay when the scene became interesting. I did not need another activity to justify being there. I remembered family conversations almost word for word. The strongest part of the afternoon was a gentle pull toward the past. I was already thinking about what came next when the harbour gave me a reason to stop. At one point, the sound of footsteps on stone became so familiar that I stopped noticing it as noise. Someone nearby was taking photos, but I found myself watching the steps facing the harbour instead. The place felt new and familiar at the same time. I think that is why the visit stayed with me long after I had left Opera House.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Nostalgia",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m16",
    title: "As a first visit,",
    body: "As a first visit, the place felt less like a postcard and more like a living part of the city. The city seemed to hold several versions of my life at once. I think that is why the visit stayed with me long after I had left Opera House. An unexpected joke from someone nearby broke the seriousness of my thoughts. A person beside me lowered their camera and simply looked, which gave me permission to do the same. I started remembering weekends from years earlier. I did not need another activity to justify being there. The feeling arrived without ceremony: a sudden rush of childhood memories. The plan was simple: meet someone, look around, and keep moving. We did none of that in a hurry. Between one conversation and the next, I became aware of the soft spray from the water.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Nostalgia",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m17",
    title: "For a moment, everyone",
    body: "For a moment, everyone seemed to pause at once before the crowd started moving again. Instead of taking the fastest route onward, I stayed long enough to see the atmosphere change. The edge of Circular Quay changed as the light moved across the scene. I compared the view with an old photo in my phone. The strongest part of the afternoon was a familiar ache of remembrance. The visit began between errands, which made the calm that followed feel even more unexpected. The broad harbour steps gave me a fixed point while everything else around it kept changing. The city seemed to hold several versions of my life at once. I still associate that feeling with Opera House in 2025. As a first visit, the place felt less like a postcard and more like a living part of the city.",
    relationship: "passingThrough",
    region: "harbour",
    emotion: "Nostalgia",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m18",
    title: "I did not need",
    body: "I did not need another activity to justify being there. The place felt new and familiar at the same time. Even now, I can picture the white sails and remember exactly how the air felt. By the time I reached the water, the noise of the rest of the city felt pleasantly distant. I had the strange feeling of being both a resident and an observer for a few minutes. I compared the view with an old photo in my phone. The white sails changed as the light moved across the scene. The strongest part of the afternoon was a quiet longing for another time. A family debated where to stand for a photo, and I quietly smiled because we had done the same thing earlier. For a moment, everyone seemed to pause at once before the crowd started moving again.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Nostalgia",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m19",
    title: "I took a longer",
    body: "I took a longer route before heading home. I did not need another activity to justify being there. Somewhere between the noise and the pauses, I noticed a tender kind of grief. A smell of rain on stone became the detail I kept noticing whenever I looked away and then back again. For a moment, everyone seemed to pause at once before the crowd started moving again. I had the strange feeling of being both a resident and an observer for a few minutes. I nearly skipped this stop because I was tired, but curiosity won the argument. Between one conversation and the next, I became aware of the cool wind off the harbour. For once, I did not feel pressured to turn the moment into something cheerful. I still associate that feeling with Opera House in 2021.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Pain",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m20",
    title: "An unexpected joke from",
    body: "An unexpected joke from someone nearby broke the seriousness of my thoughts. I took a longer route before heading home. The strongest part of the afternoon was a quiet sadness. Nothing about the setting was exotic to me, but the combination of people, weather and timing made it feel new. There was a brief pause in the day when everyone around me seemed to be doing exactly what they wanted. A person beside me lowered their camera and simply looked, which gave me permission to do the same. For once, I did not feel pressured to turn the moment into something cheerful. I still associate that feeling with Opera House in 2022. The open space beside the sails changed as the light moved across the scene. I did not need another activity to justify being there.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Pain",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m21",
    title: "I did not expect",
    body: "I did not expect the location to affect me much because I had seen photographs of it so many times. An unexpected joke from someone nearby broke the seriousness of my thoughts. The edge of Circular Quay changed as the light moved across the scene. I had expected the famous view, but the everyday movement around it was what made the visit feel real. I was surprised by how strongly I felt an ache that did not need explaining. For a moment, everyone seemed to pause at once before the crowd started moving again. The place did not fix anything, but it gave the feeling some room to breathe. I still associate that feeling with Opera House in 2023. I did not need another activity to justify being there. I took a longer route before heading home.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Pain",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m22",
    title: "An unexpected joke from",
    body: "An unexpected joke from someone nearby broke the seriousness of my thoughts. The white sails changed as the light moved across the scene. Someone stopped to tie a shoe nearby, completely unaware that the ordinary pause was part of the picture I was keeping. I took a longer route before heading home. The stone forecourt changed as the light moved across the scene. The longer I remained there, the less important my original reason for visiting seemed. I kept comparing what I had imagined from photographs with what was actually in front of me. Looking back, I remember the gentleness of the moment more than the sadness itself. The detail that survives most clearly is the sun-warmed paving. The feeling arrived without ceremony: a quiet sadness.",
    relationship: "firstTime",
    region: "forecourt",
    emotion: "Pain",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m23",
    title: "The memory stayed with",
    body: "The memory stayed with me because it made an ordinary difficult day feel honest. The detail that survives most clearly is the cool wind off the harbour. I did not expect to leave carrying a quiet sadness. For a moment, everyone seemed to pause at once before the crowd started moving again. I did not need another activity to justify being there. I remember being curious about how locals used the space rather than only how visitors photographed it. I had one of those afternoons when a short walk felt more useful than another hour indoors. I remember the sound of distant traffic almost as clearly as the view itself. I let the silence around me do some of the work. I remember the sound of street musicians almost as clearly as the view itself.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Pain",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m24",
    title: "The stone forecourt changed",
    body: "The stone forecourt changed as the light moved across the scene. The strongest part of the afternoon was a quiet sadness. I slowed down instead of trying to distract myself. By the time I reached the water, the noise of the rest of the city felt pleasantly distant. Coming from overseas, I had seen the landmark online, but the real scale was completely different. The edge of Circular Quay gave me a fixed point while everything else around it kept changing. I did not need another activity to justify being there. For a moment, everyone seemed to pause at once before the crowd started moving again. The memory stayed with me because it made an ordinary difficult day feel honest. The detail that survives most clearly is the sun-warmed paving.",
    relationship: "firstTime",
    region: "forecourt",
    emotion: "Pain",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m25",
    title: "Someone stopped to tie",
    body: "Someone stopped to tie a shoe nearby, completely unaware that the ordinary pause was part of the picture I was keeping. I stopped talking for a while. It reminded me that cities can still produce genuine surprise. I still associate that feeling with Opera House in 2021. I did not expect to leave carrying the strange excitement of seeing something differently. I was already thinking about what came next when the harbour gave me a reason to stop. I did not need another activity to justify being there. I had the strange feeling of being both a resident and an observer for a few minutes. An unexpected joke from someone nearby broke the seriousness of my thoughts. I was struck by how ordinary details, like smell of rain on stone, could make a famous place feel personal.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Wonder",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m26",
    title: "An unexpected joke from",
    body: "An unexpected joke from someone nearby broke the seriousness of my thoughts. Two friends were arguing playfully about where to eat next, making the whole place feel less like a landmark and more like a neighbourhood. The white sails changed as the light moved across the scene. The memory stayed vivid because every few minutes seemed to reveal another detail. I still associate that feeling with Opera House in 2022. I was already thinking about what came next when the harbour gave me a reason to stop. I did not need another activity to justify being there. The feeling arrived without ceremony: a rush of visual wonder. Sydney is full of views that locals can accidentally become blind to, and that afternoon corrected me. I noticed details I would normally have walked past.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Wonder",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m27",
    title: "A family debated where",
    body: "A family debated where to stand for a photo, and I quietly smiled because we had done the same thing earlier. I stopped talking for a while. The feeling arrived without ceremony: a rush of visual wonder. I watched a child point toward the water with the complete confidence that only children seem to have. That was the point when I stopped treating the visit as something I had to complete. The edge of Circular Quay changed as the light moved across the scene. As a first visit, the place felt less like a postcard and more like a living part of the city. It reminded me that cities can still produce genuine surprise. The detail that survives most clearly is the salt in the air. The white sails changed as the light moved across the scene.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Wonder",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m28",
    title: "I remember the sound",
    body: "I remember the sound of ferry engines almost as clearly as the view itself. I noticed details I would normally have walked past. The edge of Circular Quay changed as the light moved across the scene. The longer I remained there, the less important my original reason for visiting seemed. An unexpected joke from someone nearby broke the seriousness of my thoughts. I realised that seeing a place and really noticing it are not the same thing. The detail that survives most clearly is the smell of rain on stone. I went there expecting a familiar Sydney view and somehow ended up seeing it with fresh eyes. The harbour is part of everyday life here, so I liked seeing it outside the usual rush. I was surprised by how strongly I felt a rush of visual wonder.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Wonder",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m29",
    title: "The time difference was",
    body: "The time difference was still sitting in my body, which made the late afternoon feel slightly unreal. The stone forecourt changed as the light moved across the scene. The first thing I noticed was not the landmark itself but the people moving around it. The feeling arrived without ceremony: the strange excitement of seeing something differently. An unexpected joke from someone nearby broke the seriousness of my thoughts. The white sails changed as the light moved across the scene. I realised I was no longer looking for the 'best' angle; I was simply paying attention. I realised that seeing a place and really noticing it are not the same thing. It became one of the few memories from 2025 that I can replay almost scene by scene. I watched the light move across the architecture.",
    relationship: "usedTo",
    region: "forecourt",
    emotion: "Wonder",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m30",
    title: "Someone nearby was taking",
    body: "Someone nearby was taking photos, but I found myself watching the stone forecourt instead. I did not need another activity to justify being there. As a first visit, the place felt less like a postcard and more like a living part of the city. I stopped talking for a while. A person beside me lowered their camera and simply looked, which gave me permission to do the same. It reminded me that cities can still produce genuine surprise. I still associate that feeling with Opera House in 2026. The first thing I noticed was not the landmark itself but the people moving around it. Between one conversation and the next, I became aware of the bright reflections on the water. I did not expect to leave carrying a sense of astonishment.",
    relationship: "firstTime",
    region: "forecourt",
    emotion: "Wonder",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m31",
    title: "At one point, the",
    body: "At one point, the sound of camera shutters became so familiar that I stopped noticing it as noise. Nothing remarkable had to happen for the day to feel special. I think that is why the visit stayed with me long after I had left Opera House. I had the strange feeling of being both a resident and an observer for a few minutes. By the time I reached the water, the noise of the rest of the city felt pleasantly distant. Nearby, the sound of street musicians rose and faded without ever fully breaking the mood. I did not need another activity to justify being there. The feeling arrived without ceremony: a grin I could not hide. I kept pointing things out to whoever was with me. An unexpected joke from someone nearby broke the seriousness of my thoughts.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Joy",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m32",
    title: "For a few minutes,",
    body: "For a few minutes, the sound of ferry engines and the movement of people seemed to fall into one steady rhythm. An unexpected joke from someone nearby broke the seriousness of my thoughts. Sydney is full of views that locals can accidentally become blind to, and that afternoon corrected me. What began as a quick stop gradually became a moment I wanted to remember accurately. I laughed at something completely ordinary. I nearly skipped this stop because I was tired, but curiosity won the argument. I was surprised by how strongly I felt a lightness that arrived without warning. Nothing remarkable had to happen for the day to feel special. I still associate that feeling with Opera House in 2022. I remember the sound of ferry engines almost as clearly as the view itself.",
    relationship: "passingThrough",
    region: "harbour",
    emotion: "Joy",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m33",
    title: "The steps facing the",
    body: "The steps facing the harbour changed as the light moved across the scene. I remember the sound of camera shutters almost as clearly as the view itself. Everything from the accents around me to the ferry announcements made the city feel wonderfully unfamiliar. I had one of those afternoons when a short walk felt more useful than another hour indoors. The feeling arrived without ceremony: a warm sense of celebration. The visit shifted from observation into participation without any obvious turning point. Nothing remarkable had to happen for the day to feel special. I still associate that feeling with Opera House in 2023. I wandered without checking the time. A family debated where to stand for a photo, and I quietly smiled because we had done the same thing earlier.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Joy",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m34",
    title: "That was the point",
    body: "That was the point when I stopped treating the visit as something I had to complete. The harbour is part of everyday life here, so I liked seeing it outside the usual rush. I bought myself a small treat nearby. I remember checking the time before I arrived and forgetting to check it again afterward. The edge of Circular Quay changed as the light moved across the scene. A stranger laughed as they hurried past, and the tiny interruption somehow made the scene feel more human. I remember the sound of ferry engines almost as clearly as the view itself. I was surprised by how strongly I felt a burst of uncomplicated happiness. That simple afternoon still makes me smile when I think about it. I still associate that feeling with Opera House in 2024.",
    relationship: "passingThrough",
    region: "harbour",
    emotion: "Joy",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m35",
    title: "I remember how easy",
    body: "I remember how easy it felt to enjoy the city without needing a reason. Even now, I can picture the broad harbour steps and remember exactly how the air felt. The feeling arrived without ceremony: a grin I could not hide. The harbour is part of everyday life here, so I liked seeing it outside the usual rush. I did not need another activity to justify being there. Every few minutes, a different sound — especially footsteps on stone — changed the atmosphere slightly. An unexpected joke from someone nearby broke the seriousness of my thoughts. At one point, the sound of ferry engines became so familiar that I stopped noticing it as noise. The visit began between errands, which made the calm that followed feel even more unexpected. I took far too many photos.",
    relationship: "passingThrough",
    region: "steps",
    emotion: "Joy",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m36",
    title: "The water beyond the",
    body: "The water beyond the ferry wharves gave me a fixed point while everything else around it kept changing. A person beside me lowered their camera and simply looked, which gave me permission to do the same. I called a friend before I had even left. Nothing remarkable had to happen for the day to feel special. I still associate that feeling with Opera House in 2026. I was surprised by how strongly I felt a lightness that arrived without warning. I did not need another activity to justify being there. I was already thinking about what came next when the harbour gave me a reason to stop. Nearby, the sound of footsteps on stone rose and faded without ever fully breaking the mood. I had the strange feeling of being both a resident and an observer for a few minutes.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Joy",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m37",
    title: "I did not need",
    body: "I did not need another activity to justify being there. The strongest part of the afternoon was a deep sense of affection. At one point, the sound of ferry engines became so familiar that I stopped noticing it as noise. Being new to Sydney made me notice details that I suspect a frequent visitor could easily overlook. For a few minutes, the sound of small bursts of laughter and the movement of people seemed to fall into one steady rhythm. We shared food and watched the harbour together. An unexpected joke from someone nearby broke the seriousness of my thoughts. I remember less about the itinerary than I remember feeling close. I still associate that feeling with Opera House in 2021. I had one of those afternoons when a short walk felt more useful than another hour indoors.",
    relationship: "firstTime",
    region: "harbour",
    emotion: "Love",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m38",
    title: "The strongest part of",
    body: "The strongest part of the afternoon was a deep sense of affection. I noticed how naturally our conversation slowed down. The stone forecourt changed as the light moved across the scene. I remember the sound of ferry engines almost as clearly as the view itself. That was the point when I stopped treating the visit as something I had to complete. The visit began between errands, which made the calm that followed feel even more unexpected. I watched a child point toward the water with the complete confidence that only children seem to have. I kept comparing what I had imagined from photographs with what was actually in front of me. It was a small moment, but it made the city feel unusually personal. It became one of the few memories from 2022 that I can replay almost scene by scene.",
    relationship: "passingThrough",
    region: "forecourt",
    emotion: "Love",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m39",
    title: "For a moment, everyone",
    body: "For a moment, everyone seemed to pause at once before the crowd started moving again. The air carried the cool wind off the harbour, while the broad harbour steps held most of my attention. Somewhere between the noise and the pauses, I noticed a deep sense of affection. The place became meaningful because of the person beside me. I still associate that feeling with Opera House in 2023. I was still learning the city's rhythm, so even ordinary details felt surprisingly vivid. I realised I was no longer looking for the 'best' angle; I was simply paying attention. The broad harbour steps changed as the light moved across the scene. I noticed how naturally our conversation slowed down. I had one of those afternoons when a short walk felt more useful than another hour indoors.",
    relationship: "usedTo",
    region: "steps",
    emotion: "Love",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m40",
    title: "We took turns choosing",
    body: "We took turns choosing what to photograph. Someone nearby was taking photos, but I found myself watching the stone forecourt instead. The broad harbour steps stayed in view while the crowd, weather and sounds kept rearranging the moment. I did not need another activity to justify being there. I remember less about the itinerary than I remember feeling close. The detail that survives most clearly is the salt in the air. I was surprised by how strongly I felt a tenderness I did not want to rush. I remember being curious about how locals used the space rather than only how visitors photographed it. A small change in the weather turned an unremarkable outing into the part of the day I remember most. An unexpected joke from someone nearby broke the seriousness of my thoughts.",
    relationship: "firstTime",
    region: "forecourt",
    emotion: "Love",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m41",
    title: "A person beside me",
    body: "A person beside me lowered their camera and simply looked, which gave me permission to do the same. I did not need another activity to justify being there. I did not expect the location to affect me much because I had seen photographs of it so many times. I reached for their hand without thinking. I had expected the famous view, but the everyday movement around it was what made the visit feel real. The stone forecourt changed as the light moved across the scene. The strongest part of the afternoon was a feeling of caring that filled the afternoon. Years later, the strongest part of the memory is still the sense of togetherness. The detail that survives most clearly is the smell of rain on stone. I remember the sound of camera shutters almost as clearly as the view itself.",
    relationship: "firstTime",
    region: "forecourt",
    emotion: "Love",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m42",
    title: "Years later, the strongest",
    body: "Years later, the strongest part of the memory is still the sense of togetherness. I still associate that feeling with Opera House in 2026. I remember checking the time before I arrived and forgetting to check it again afterward. I reached for their hand without thinking. I did not need another activity to justify being there. Coming from overseas, I had seen the landmark online, but the real scale was completely different. For a moment, everyone seemed to pause at once before the crowd started moving again. The curved shells of the building changed as the light moved across the scene. Underneath everything else, there was a quiet feeling of being close to someone. At one point, the sound of water moving against the quay became so familiar that I stopped noticing it as noise.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Love",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m43",
    title: "I nearly skipped this",
    body: "I nearly skipped this stop because I was tired, but curiosity won the argument. The feeling arrived without ceremony: a gentle pull toward the past. An unexpected joke from someone nearby broke the seriousness of my thoughts. I compared the view with an old photo in my phone. I was struck by how ordinary details, like soft spray from the water, could make a famous place feel personal. A family debated where to stand for a photo, and I quietly smiled because we had done the same thing earlier. I kept comparing what I had imagined from photographs with what was actually in front of me. The city seemed to hold several versions of my life at once. I still associate that feeling with Opera House in 2021. I did not need another activity to justify being there.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Nostalgia",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m44",
    title: "The broad harbour steps",
    body: "The broad harbour steps changed as the light moved across the scene. I started remembering weekends from years earlier. I remember the sound of small bursts of laughter almost as clearly as the view itself. The place felt new and familiar at the same time. I still associate that feeling with Opera House in 2022. The longer I remained there, the less important my original reason for visiting seemed. I was travelling without a strict schedule, which gave me permission to stay when the scene became interesting. An unexpected joke from someone nearby broke the seriousness of my thoughts. Someone stopped to tie a shoe nearby, completely unaware that the ordinary pause was part of the picture I was keeping. The feeling arrived without ceremony: a warm sense of returning.",
    relationship: "firstTime",
    region: "steps",
    emotion: "Nostalgia",
    year: "2022",
    place: "Opera House",
  },
  {
    id: "m45",
    title: "An unexpected joke from",
    body: "An unexpected joke from someone nearby broke the seriousness of my thoughts. Between one conversation and the next, I became aware of the cool wind off the harbour. The city seemed to hold several versions of my life at once. I think that is why the visit stayed with me long after I had left Opera House. What began as a quick stop gradually became a moment I wanted to remember accurately. For a moment, everyone seemed to pause at once before the crowd started moving again. I compared the view with an old photo in my phone. Somewhere between the noise and the pauses, I noticed a quiet longing for another time. As a first visit, the place felt less like a postcard and more like a living part of the city. I remember the sound of muffled conversations almost as clearly as the view itself.",
    relationship: "passingThrough",
    region: "harbour",
    emotion: "Nostalgia",
    year: "2023",
    place: "Opera House",
  },
  {
    id: "m46",
    title: "I noticed how much",
    body: "I noticed how much the city had changed around an unchanged feeling. The place felt new and familiar at the same time. It became one of the few memories from 2024 that I can replay almost scene by scene. That was the point when I stopped treating the visit as something I had to complete. The feeling arrived without ceremony: a quiet longing for another time. An unexpected joke from someone nearby broke the seriousness of my thoughts. Two friends were arguing playfully about where to eat next, making the whole place feel less like a landmark and more like a neighbourhood. I had the strange feeling of being both a resident and an observer for a few minutes. The stone forecourt changed as the light moved across the scene. The white sails changed as the light moved across the scene.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Nostalgia",
    year: "2024",
    place: "Opera House",
  },
  {
    id: "m47",
    title: "At one point, the",
    body: "At one point, the sound of water moving against the quay became so familiar that I stopped noticing it as noise. The white sails changed as the light moved across the scene. An unexpected joke from someone nearby broke the seriousness of my thoughts. I compared the view with an old photo in my phone. Someone held a coffee in both hands against the wind, and that tiny gesture made the weather suddenly noticeable. The place felt new and familiar at the same time. I still associate that feeling with Opera House in 2025. I went there expecting a familiar Sydney view and somehow ended up seeing it with fresh eyes. The strongest part of the afternoon was a familiar ache of remembrance. I had the strange feeling of being both a resident and an observer for a few minutes.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Nostalgia",
    year: "2025",
    place: "Opera House",
  },
  {
    id: "m48",
    title: "The longer I remained",
    body: "The longer I remained there, the less important my original reason for visiting seemed. The harbour is part of everyday life here, so I liked seeing it outside the usual rush. The white sails gave me a fixed point while everything else around it kept changing. I remember the sound of footsteps on stone almost as clearly as the view itself. The city seemed to hold several versions of my life at once. The detail that survives most clearly is the smell of rain on stone. I was surprised by how strongly I felt a warm sense of returning. I started remembering weekends from years earlier. I was already thinking about what came next when the harbour gave me a reason to stop. For a moment, everyone seemed to pause at once before the crowd started moving again.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Nostalgia",
    year: "2026",
    place: "Opera House",
  },
  {
    id: "m49",
    title: "I did not expect",
    body: "I did not expect to leave carrying a tender kind of grief. The place did not fix anything, but it gave the feeling some room to breathe. The detail that survives most clearly is the smell of rain on stone. Everything from the accents around me to the ferry announcements made the city feel wonderfully unfamiliar. I let the silence around me do some of the work. I arrived earlier than I needed to, with no real plan beyond walking until something caught my attention. I did not need another activity to justify being there. Someone held a coffee in both hands against the wind, and that tiny gesture made the weather suddenly noticeable. An unexpected joke from someone nearby broke the seriousness of my thoughts. The white sails changed as the light moved across the scene.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Pain",
    year: "2021",
    place: "Opera House",
  },
  {
    id: "m50",
    title: "For once, I did",
    body: "For once, I did not feel pressured to turn the moment into something cheerful. The detail that survives most clearly is the salt in the air. I remember being curious about how locals used the space rather than only how visitors photographed it. I nearly skipped this stop because I was tired, but curiosity won the argument. The white sails changed as the light moved across the scene. I slowed down instead of trying to distract myself. A person beside me lowered their camera and simply looked, which gave me permission to do the same. The longer I remained there, the less important my original reason for visiting seemed. I was surprised by how strongly I felt a tender kind of grief. I remember the sound of distant traffic almost as clearly as the view itself.",
    relationship: "firstTime",
    region: "sails",
    emotion: "Pain",
    year: "2022",
    place: "Opera House",
  }
];

export function memoryCountLabel(count = memories.length) {
  return `${count} memories live here`;
}
